apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ujhvjkil
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ujhvjkil:b01980203d8b16c392588db7df6fb7988acad69b@sha256:8b6a99a3762187ac48e82058b9155137a09fce0935efa3456844b89f5e7dc594
          name: container-image
